import type { RepositorySnapshot } from "../transit/model";

const now = new Date("2026-07-21T12:00:00.000Z");
const minutesAgo = (minutes: number) =>
  new Date(now.getTime() - minutes * 60_000).toISOString();

export const demoSnapshot: RepositorySnapshot = {
  repository: {
    id: "demo-orbit-console",
    name: "orbit-console",
    fullName: "signalworks/orbit-console",
    description: "A fictional mission-control interface for orbital freight.",
    defaultBranch: "main",
    url: "https://github.com/signalworks/orbit-console",
    stars: 428,
  },
  branches: [
    { name: "main", protected: true, updatedAt: minutesAgo(3) },
    { name: "develop", protected: false, updatedAt: minutesAgo(9) },
    { name: "feature/radar-overlays", protected: false, updatedAt: minutesAgo(11) },
    { name: "feature/depot-timeline", protected: false, updatedAt: minutesAgo(24) },
    { name: "release/1.8.0", protected: false, updatedAt: minutesAgo(40) },
    { name: "hotfix/check-run-timeout", protected: false, updatedAt: minutesAgo(17) },
  ],
  commits: [
    [
      "c1",
      "Tune train path easing for long routes",
      "Asha",
      "feature/radar-overlays",
      5,
    ],
    ["c2", "Add depot arrival telemetry panel", "Vikram", "feature/depot-timeline", 14],
    ["c3", "Patch workflow timeout indicator", "Mira", "hotfix/check-run-timeout", 18],
    ["c4", "Prepare 1.8.0 release notes", "Noor", "release/1.8.0", 37],
    ["c5", "Merge approved signal state copy", "Ishan", "main", 61],
  ].map(([id, message, author, branch, min]) => ({
    id: String(id),
    message: String(message),
    author: String(author),
    branch: String(branch),
    committedAt: minutesAgo(Number(min)),
  })),
  pullRequests: [
    {
      id: "901",
      number: 901,
      title: "Radar overlays for active workstreams",
      branch: "feature/radar-overlays",
      author: "Asha",
      state: "open",
      reviewState: "approved",
      checkState: "success",
      commitCount: 7,
      url: "https://github.com/signalworks/orbit-console/pull/901",
      createdAt: minutesAgo(600),
      updatedAt: minutesAgo(4),
    },
    {
      id: "904",
      number: 904,
      title: "Depot timeline drawer with keyboard focus",
      branch: "feature/depot-timeline",
      author: "Vikram",
      state: "open",
      reviewState: "pending",
      checkState: "pending",
      commitCount: 4,
      url: "https://github.com/signalworks/orbit-console/pull/904",
      createdAt: minutesAgo(420),
      updatedAt: minutesAgo(13),
    },
    {
      id: "908",
      number: 908,
      title: "Fix timeout signal on public workflow runs",
      branch: "hotfix/check-run-timeout",
      author: "Mira",
      state: "open",
      reviewState: "changes-requested",
      checkState: "failed",
      commitCount: 2,
      url: "https://github.com/signalworks/orbit-console/pull/908",
      createdAt: minutesAgo(110),
      updatedAt: minutesAgo(16),
    },
    {
      id: "887",
      number: 887,
      title: "Merge signal legend refinements",
      branch: "main",
      author: "Ishan",
      state: "merged",
      reviewState: "approved",
      checkState: "success",
      commitCount: 5,
      url: "https://github.com/signalworks/orbit-console/pull/887",
      createdAt: minutesAgo(900),
      updatedAt: minutesAgo(58),
    },
  ],
  workflowRuns: [
    {
      id: "wf-1",
      name: "Transit checks",
      status: "success",
      branch: "feature/radar-overlays",
      updatedAt: minutesAgo(6),
    },
    {
      id: "wf-2",
      name: "Browser smoke",
      status: "failed",
      branch: "hotfix/check-run-timeout",
      updatedAt: minutesAgo(16),
    },
  ],
  releases: [
    {
      id: "rel-18",
      name: "Orbit Console 1.8.0",
      tagName: "v1.8.0",
      url: "https://github.com/signalworks/orbit-console/releases/tag/v1.8.0",
      publishedAt: minutesAgo(42),
    },
  ],
  deployments: [
    {
      id: "dep-prod",
      environment: "public display",
      state: "success",
      branch: "release/1.8.0",
      updatedAt: minutesAgo(35),
    },
  ],
  contributors: [
    { id: "asha", name: "Asha", contributions: 38 },
    { id: "vikram", name: "Vikram", contributions: 26 },
    { id: "mira", name: "Mira", contributions: 19 },
    { id: "noor", name: "Noor", contributions: 17 },
  ],
  fetchedAt: now.toISOString(),
  warnings: [],
};
